-- Arquivo descontinuado.
--
-- Este schema pertencia ao protótipo de loja online da versão anterior do
-- projeto. O modelo de dados atual do Fluxen ERP está em db/schema.sql, e o
-- dicionário de dados completo em docs/tecnico/02-modelo-de-dados.md.
--
-- Este arquivo pode ser excluído.
