import type { LimitedStage, ScenarioDef } from '../types';

const WIP = (ready: number, analysis: number, dev: number, review: number, test: number, uat: number, deploy: number): Record<LimitedStage, number> => ({
  ready, analysis, dev, review, test, uat, deploy,
});

/** 8 cenários de campanha — ordem define a progressão */
export const SCENARIOS: ScenarioDef[] = [
  {
    id: 'startup', order: 1, name: 'Startup', subtitle: 'Lançamento do MVP',
    description: 'Uma equipe pequena, dinheiro contado e um investidor esperando o MVP. Cada pessoa precisa cobrir várias funções.',
    objective: 'Entregue o MVP rapidamente sem queimar o caixa.',
    icon: 'Rocket', accent: '#a78bfa', segments: ['startup'],
    team: ['po', 'analyst', 'fullstack', 'fullstack', 'qa', 'devops'],
    startingCash: 140000, initialBacklog: 12, arrivalRate: 0.9, initialTechDebt: 8, initialClientSat: 75,
    typeWeights: { feature: 6, ux: 2, bug: 1, improvement: 1.5, infra: 0.6, integration: 0.8 },
    classWeights: { standard: 7, fixed: 1, expedite: 0.4, intangible: 0.6 },
    wipLimits: WIP(4, 2, 3, 2, 2, 2, 2), autoPull: true, infraCostPerDay: 400,
    incidentSeverityMult: 0.8, techDebtDrift: 0.15, recommendedDays: 20,
    goals: [
      { metric: 'delivered', target: 12, label: 'Entregar 12 demandas', cmp: 'gte' },
      { metric: 'profit', target: 0, label: 'Terminar com lucro positivo', cmp: 'gte' },
      { metric: 'clientSat', target: 70, label: 'Satisfação do cliente ≥ 70%', cmp: 'gte' },
    ],
    tips: ['Pessoas generalistas podem cobrir gargalos, mas com menos produtividade.', 'Com equipe pequena, WIP baixo é essencial.'],
  },
  {
    id: 'saas', order: 2, name: 'Empresa SaaS', subtitle: 'Muitos clientes, muitas demandas',
    description: 'Centenas de assinantes pedindo features enquanto bugs chegam todos os dias. O desafio é equilibrar evolução e estabilidade.',
    objective: 'Equilibre novas features e correção de bugs mantendo os clientes satisfeitos.',
    icon: 'Briefcase', accent: '#818cf8', segments: ['saas', 'startup', 'retail', 'industry'],
    team: ['po', 'analyst', 'frontend', 'backend', 'fullstack', 'qa', 'qa', 'devops'],
    startingCash: 220000, initialBacklog: 16, arrivalRate: 1.6, initialTechDebt: 20, initialClientSat: 72,
    typeWeights: { feature: 4, bug: 3, improvement: 2.5, ux: 1, techdebt: 1, integration: 1, infra: 0.6, security: 0.5 },
    classWeights: { standard: 7, fixed: 1.2, expedite: 0.8, intangible: 0.8 },
    wipLimits: WIP(5, 3, 4, 2, 3, 2, 2), autoPull: true, infraCostPerDay: 900,
    incidentSeverityMult: 1, techDebtDrift: 0.2, recommendedDays: 30,
    goals: [
      { metric: 'clientSat', target: 75, label: 'Satisfação do cliente ≥ 75%', cmp: 'gte' },
      { metric: 'escapedBugs', target: 6, label: 'No máximo 6 bugs escapados', cmp: 'lte' },
      { metric: 'revenue', target: 300000, label: 'Receita ≥ R$ 300 mil', cmp: 'gte' },
    ],
    tips: ['Bugs não corrigidos corroem a satisfação.', 'Receita recorrente favorece entregar cedo.'],
  },
  {
    id: 'fintech', order: 3, name: 'Fintech', subtitle: 'Segurança e disponibilidade',
    description: 'Transações financeiras em tempo real. Um incidente custa caro, e auditorias aparecem sem aviso.',
    objective: 'Entregue com qualidade: poucos incidentes, segurança em dia e alta disponibilidade.',
    icon: 'Wallet', accent: '#34d399', segments: ['fintech', 'bank'],
    team: ['po', 'analyst', 'backend', 'backend', 'fullstack', 'qa', 'devops', 'architect'],
    startingCash: 260000, initialBacklog: 14, arrivalRate: 1.4, initialTechDebt: 18, initialClientSat: 70,
    typeWeights: { feature: 4, security: 2.5, bug: 1.5, integration: 1.5, infra: 1, improvement: 1, techdebt: 0.8 },
    classWeights: { standard: 6, fixed: 2, expedite: 0.8, intangible: 1 },
    eventCategoryWeights: { incident: 1.4, tech: 1.2 },
    wipLimits: WIP(4, 3, 4, 2, 3, 2, 2), autoPull: true, infraCostPerDay: 1400,
    incidentSeverityMult: 1.5, techDebtDrift: 0.2, recommendedDays: 30,
    goals: [
      { metric: 'escapedBugs', target: 4, label: 'No máximo 4 bugs em produção', cmp: 'lte' },
      { metric: 'clientSat', target: 75, label: 'Satisfação do cliente ≥ 75%', cmp: 'gte' },
      { metric: 'profit', target: 50000, label: 'Lucro ≥ R$ 50 mil', cmp: 'gte' },
    ],
    tips: ['Invista em testes e code review.', 'Demandas Fixed Date regulatórias geram multas pesadas.'],
  },
  {
    id: 'hospital', order: 4, name: 'Sistema Hospitalar', subtitle: 'Falhas com impacto crítico',
    description: 'O sistema apoia o atendimento de pacientes. Incidentes afetam vidas e a reputação do hospital.',
    objective: 'Zero tolerância a instabilidade: responda rápido a incidentes e mantenha a qualidade.',
    icon: 'Hospital', accent: '#f87171', segments: ['hospital', 'healthplan'],
    team: ['po', 'analyst', 'backend', 'fullstack', 'frontend', 'qa', 'qa', 'devops', 'dba'],
    startingCash: 250000, initialBacklog: 14, arrivalRate: 1.4, initialTechDebt: 25, initialClientSat: 70,
    typeWeights: { feature: 3.5, bug: 2, security: 1.5, integration: 1.5, improvement: 1.5, infra: 1, ux: 0.8 },
    classWeights: { standard: 6, fixed: 1.5, expedite: 1.2, intangible: 0.8 },
    eventCategoryWeights: { incident: 1.6 },
    wipLimits: WIP(4, 3, 4, 2, 3, 2, 2), autoPull: true, infraCostPerDay: 1200,
    incidentSeverityMult: 2, techDebtDrift: 0.25, recommendedDays: 30,
    goals: [
      { metric: 'incidents', target: 4, label: 'No máximo 4 incidentes', cmp: 'lte' },
      { metric: 'clientSat', target: 72, label: 'Satisfação do cliente ≥ 72%', cmp: 'gte' },
      { metric: 'escapedBugs', target: 5, label: 'No máximo 5 bugs escapados', cmp: 'lte' },
    ],
    tips: ['Incidentes abertos derrubam a satisfação a cada dia.', 'Mantenha capacidade livre para Expedite.'],
  },
  {
    id: 'healthplan', order: 5, name: 'Operadora de Saúde', subtitle: 'Integrações por toda parte',
    description: 'Prestadores, laboratórios, hospitais e reguladores. Quase tudo depende de APIs externas.',
    objective: 'Gerencie dependências e bloqueios sem deixar o Lead Time explodir.',
    icon: 'HeartPulse', accent: '#fb7185', segments: ['healthplan', 'hospital', 'government'],
    team: ['po', 'analyst', 'analyst', 'backend', 'backend', 'fullstack', 'qa', 'devops', 'dba'],
    startingCash: 240000, initialBacklog: 15, arrivalRate: 1.4, initialTechDebt: 22, initialClientSat: 70,
    typeWeights: { integration: 4, feature: 3, bug: 1.5, security: 1, improvement: 1, infra: 0.8 },
    classWeights: { standard: 6, fixed: 2, expedite: 0.7, intangible: 0.7 },
    wipLimits: WIP(5, 3, 4, 2, 3, 2, 2), autoPull: true, infraCostPerDay: 1000,
    incidentSeverityMult: 1.3, techDebtDrift: 0.2, recommendedDays: 30,
    goals: [
      { metric: 'leadTime', target: 12, label: 'Lead Time médio ≤ 12 dias', cmp: 'lte' },
      { metric: 'delivered', target: 20, label: 'Entregar 20 demandas', cmp: 'gte' },
      { metric: 'clientSat', target: 70, label: 'Satisfação do cliente ≥ 70%', cmp: 'gte' },
    ],
    tips: ['Integrações bloqueiam com frequência: escale bloqueios.', 'Evite puxar cards dependentes antes das dependências.'],
  },
  {
    id: 'ecommerce', order: 6, name: 'E-commerce', subtitle: 'Black Friday',
    description: 'A Black Friday está chegando. Na semana do evento, a demanda e os incidentes explodem.',
    objective: 'Prepare a plataforma antes do pico e sobreviva à Black Friday.',
    icon: 'ShoppingCart', accent: '#22d3ee', segments: ['ecommerce', 'retail'],
    team: ['po', 'analyst', 'frontend', 'frontend', 'backend', 'fullstack', 'qa', 'qa', 'devops'],
    startingCash: 230000, initialBacklog: 16, arrivalRate: 1.5, initialTechDebt: 20, initialClientSat: 74,
    typeWeights: { feature: 4, ux: 2, improvement: 2, bug: 1.5, infra: 1.5, integration: 1 },
    classWeights: { standard: 6, fixed: 2.2, expedite: 0.8, intangible: 0.6 },
    wipLimits: WIP(5, 3, 4, 2, 3, 2, 2), autoPull: true, infraCostPerDay: 1100,
    incidentSeverityMult: 1.4, techDebtDrift: 0.2, recommendedDays: 30,
    surges: [{ fromDay: 19, toDay: 25, arrivalMult: 2.3, label: 'BLACK FRIDAY' }],
    eventCategoryWeights: { incident: 1.3, client: 1.2 },
    goals: [
      { metric: 'revenue', target: 350000, label: 'Receita ≥ R$ 350 mil', cmp: 'gte' },
      { metric: 'clientSat', target: 70, label: 'Satisfação do cliente ≥ 70%', cmp: 'gte' },
      { metric: 'incidents', target: 5, label: 'No máximo 5 incidentes', cmp: 'lte' },
    ],
    tips: ['Entregue infraestrutura antes do dia 19.', 'Receita recorrente dispara durante o pico.'],
  },
  {
    id: 'legacy', order: 7, name: 'Projeto Legado', subtitle: 'Dívida técnica monumental',
    description: 'Um sistema de 15 anos, sem testes, com deploys manuais. A dívida técnica cresce todos os dias.',
    objective: 'Reduza a dívida técnica sem parar de entregar valor.',
    icon: 'Construction', accent: '#f59e0b', segments: ['industry', 'government', 'bank'],
    team: ['po', 'analyst', 'backend', 'backend', 'fullstack', 'qa', 'devops', 'architect'],
    startingCash: 230000, initialBacklog: 15, arrivalRate: 1.2, initialTechDebt: 65, initialClientSat: 62,
    typeWeights: { techdebt: 3, feature: 3, bug: 2.5, improvement: 1, infra: 1.2, security: 1 },
    classWeights: { standard: 6, fixed: 1, expedite: 0.8, intangible: 2 },
    eventCategoryWeights: { tech: 1.6 },
    wipLimits: WIP(4, 3, 4, 2, 3, 2, 2), autoPull: true, infraCostPerDay: 1300,
    incidentSeverityMult: 1.2, techDebtDrift: 0.6, recommendedDays: 30,
    goals: [
      { metric: 'techDebt', target: 40, label: 'Dívida técnica ≤ 40%', cmp: 'lte' },
      { metric: 'delivered', target: 15, label: 'Entregar 15 demandas', cmp: 'gte' },
      { metric: 'clientSat', target: 65, label: 'Satisfação do cliente ≥ 65%', cmp: 'gte' },
    ],
    tips: ['Dívida técnica reduz a produtividade e aumenta os bugs.', 'Cards Intangible pagam dívida.'],
  },
  {
    id: 'transformation', order: 8, name: 'Transformação Ágil', subtitle: 'Do caos ao fluxo',
    description: 'Você herdou um time que começa tudo e termina pouco. Sem limites de WIP, todos no desenvolvimento e o quadro lotado.',
    objective: 'Implante limites de WIP, realoque o time e estabilize o fluxo.',
    icon: 'Workflow', accent: '#38bdf8', segments: ['saas', 'retail', 'bank', 'industry'],
    team: ['po', 'analyst', 'frontend', 'backend', 'backend', 'fullstack', 'qa', 'devops'],
    startingCash: 210000, initialBacklog: 14, arrivalRate: 1.4, initialTechDebt: 35, initialClientSat: 58,
    typeWeights: { feature: 4, bug: 2, improvement: 2, techdebt: 1, integration: 1, ux: 1 },
    classWeights: { standard: 7, fixed: 1.2, expedite: 1, intangible: 0.6 },
    wipLimits: WIP(20, 20, 20, 20, 20, 20, 20), autoPull: false, infraCostPerDay: 1000,
    incidentSeverityMult: 1, techDebtDrift: 0.3, recommendedDays: 30,
    prestartedCards: 16, chaoticStart: true,
    goals: [
      { metric: 'leadTime', target: 10, label: 'Lead Time médio ≤ 10 dias', cmp: 'lte' },
      { metric: 'throughput', target: 1, label: 'Throughput ≥ 1 card/dia', cmp: 'gte' },
      { metric: 'teamMorale', target: 65, label: 'Moral da equipe ≥ 65%', cmp: 'gte' },
    ],
    tips: ['Comece definindo limites de WIP realistas.', 'Ligue o Auto-pull quando o fluxo estiver estável.'],
  },
];

export const SCENARIO_MAP = Object.fromEntries(SCENARIOS.map((s) => [s.id, s])) as Record<string, ScenarioDef>;
